Add Bootstrap css and Lato font family
hafedEfheij/Capstone-Project-1 pull request #1
Opened 2023-01-06 08:49 UTC by hafedEfheij

2023-01-06 13:12 UTC, binhussen requested changes
Hi @hafedEfheij , 

Good job so far!
There are some issues that you still need to work on to prepare your project for the final evaluation but you are almost there!
<img src="https://media0.giphy.com/media/UdaSUYClr92cjWpeVx/giphy.gif"/>

## Highlights

- All linter checks passed ✔️
- Descriptive pull request ✔️
- Used GitHub flow ✔️


## Suggested changes
- kindly add the video presentation as the [requirement](https://github.com/microverseinc/curriculum-html-css/blob/main/capstone/html_capstone.md)👌👍
- Kindly Keep semantic tags for readability and search engines👌👌

You can use as many of my suggestions as you want. If there is anything you would like to skip - feel free to do that. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

2023-01-06 13:12 UTC, binhussen commented on index.html
> +        </header>
- Kindly keep the semantic flows `header` representing your heading part, not a specific header.👍👌
- I think it is better to rap the `section`'s with `main` for more readability 👍

2023-01-06 13:12 UTC, binhussen commented on index.html
> +        <img src="./assets/images/airbnb.png" />
- Kindly use `alt` for each of your images for readability and accessibility👌👍

2023-01-06 13:12 UTC, binhussen commented on README.md
>  ## 🚀 Live Demo <a name="live-demo"></a>
- Kindly Add a video presentation in the code review summary which includes the features of the project within the maximum length of the video is 5 minutes. 👌👍

2023-01-06 13:12 UTC, binhussen commented on about.html
> +    <footer id="desktop-footer">
- Kindly collect the footer one `footer` tag, becouse you have only one fooer per page for semantic reasons👌👍

2023-01-06 13:12 UTC, binhussen commented on assets/stylesheets/index.css
> +  }
- [Optional] Kindly use class to make your style reuasable👌👍

2023-01-06 17:37 UTC, huseyinbiyik requested changes
Hi @hafedEfheij,

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't been addressed yet.
![tenor](https://user-images.githubusercontent.com/25887253/205415161-00e79d1b-af68-4f10-9b2c-265f460dc5da.gif)

 ## Highlights
- Good job with the implementation. It looks wonderful 👨‍🎨

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-06 17:37 UTC, huseyinbiyik commented on about.html
> +        <img src="./assets/images/mozilla.png" />
Please add alt attributes for each `<img>` element in your pages as the previous reviewer requested. This is important for the accessibility and SEO of your web pages.

2023-01-06 17:37 UTC, huseyinbiyik commented on assets/stylesheets/about.css
> +@media screen and (min-width: 768px) {
[OPTIONAL] This line repeats many times in your CSS files. Kindly follow the mobile-first approach and use the desktop media query once in a file to make your code readable and DRY.

2023-01-06 17:37 UTC, huseyinbiyik commented on index.html
> +      <div id="mobile-menu" class="d-none flex-column">
[OPTIONAL] Kindly fix your mobile as seen in the design provided. It needs to be transparent. And also there is a bug when you the page to the bottom. Please check the gif below.
![Screen Recording 2023-01-06 at 8 21 13 PM](https://user-images.githubusercontent.com/25887253/211066250-ad7a5da7-163f-4eb0-a1d0-39201b697f8b.gif)

Cindy's design:
<img width="822" alt="Screenshot 2023-01-06 at 8 24 17 PM" src="https://user-images.githubusercontent.com/25887253/211066334-57425f2d-49e1-4c32-8b0f-7c7308530f14.png">

2023-01-06 18:57 UTC, Nemwel-Boniface requested changes
## Hello @hafedEfheij         :wave: , 
I'm Nemwel your reviewer for this PR :man_beard: 

Great job addressing some of the changes that were requested by a previous reviewer :clap: 
There are some issues that you still need to work on to go to the next project but you are almost there!

![](https://media.giphy.com/media/KyBesf8kNT6s88SEgb/giphy.gif)
## Highlights

Great job setting up the correct linters ✔️ 
Professional documentation ✔️ 
Correct workflow ✔️ 
Meaningful commit messages ✔️  


## ♻️ Required Changes ♻️


- [ ] You have done a great job taking the presentation video as requested of you by the previous reviewer. However, in order for it to meet all the project requirements, you are supposed to show:
   -  a description of the project. (This includes the [project requirements](https://github.com/microverseinc/curriculum-html-css/blob/main/capstone/html_capstone.md) as provided by Microverse)
   - a demo of the project features (Which you did a great job :fire: )
   - you should also highlight some interesting piece of code or something you built that you are very proud of. 

The video currently does not showcase all the above three cases. Also, it is a strict requirement that the video is not more than 5 minutes. Kindly retake the video and this time round make sure all three have been covered.

![image](https://user-images.githubusercontent.com/86318284/208606238-f5fa2ae6-d1f7-42e6-b542-c7c83496fd1f.png)




_Check the comments under the review._

## [Optional] suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding! :partying_face: 👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me **@Nemwel-Boniface** in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-06 19:15 UTC, hafedEfheij commented
@Nemwel-Boniface thanks for your review, However, this wasn't mentioned in the previous review, I mean I thought the reviews should be related. I mean that was my third review request. thanks again

2023-01-06 19:19 UTC, Nemwel-Boniface commented
Hello @hafedEfheij the last reviewer @huseyinbiyik mentioned it here

![image](https://user-images.githubusercontent.com/86318284/211084014-e3e47e45-c806-4768-abca-d6f2211267ac.png)

2023-01-06 19:22 UTC, hafedEfheij commented
@Nemwel-Boniface Thanks for reolying. yes that was the first reviewer because I did not put the link.

2023-01-07 19:44 UTC, frank1738 approved these changes
Hi @hafedEfheij , 

Excellent work. Your project is complete!  There is nothing else to say other than... it's time to merge \
Congratulations! 🎉 

<img src="https://media4.giphy.com/media/1uC8xfkZRi7Kw/giphy.gif"/>



## Highlights

✅ Correct use of Github workflow
✅ No linter error
✅ Good Design 👍 
✅ Professional Documentation 👍 

## Optional suggestions

N/A

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-07 19:47 UTC, merged